// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
    defaultValue: 'AIza' 'SyBZxQCjlqdWkzKlNqc8fSM1eTe3aY0w-Kc',
  );

  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: 'AIza' 'SyBShQzU3VBSeTe01Rkdu23rMiRyjT8Qmxs',
  );

  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
    defaultValue: 'AIza' 'SyBJ4YUMlrZrQ0_PRK-4wLhDvzRitCEf7IQ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:255731454217:web:f5d1cb14c99418645cc3d8',
    messagingSenderId: '255731454217',
    projectId: 'digital-burnout-821da',
    authDomain: 'digital-burnout-821da.firebaseapp.com',
    storageBucket: 'digital-burnout-821da.firebasestorage.app',
    measurementId: 'G-MX81GBRREH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:255731454217:android:a41e28f36ac2e0705cc3d8',
    messagingSenderId: '255731454217',
    projectId: 'digital-burnout-821da',
    storageBucket: 'digital-burnout-821da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:255731454217:ios:3e83bd79cc45a8175cc3d8',
    messagingSenderId: '255731454217',
    projectId: 'digital-burnout-821da',
    storageBucket: 'digital-burnout-821da.firebasestorage.app',
    iosBundleId: 'com.example.flutterCatalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:255731454217:ios:3e83bd79cc45a8175cc3d8',
    messagingSenderId: '255731454217',
    projectId: 'digital-burnout-821da',
    storageBucket: 'digital-burnout-821da.firebasestorage.app',
    iosBundleId: 'com.example.flutterCatalog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:255731454217:web:ba1e73cd28a26dab5cc3d8',
    messagingSenderId: '255731454217',
    projectId: 'digital-burnout-821da',
    authDomain: 'digital-burnout-821da.firebaseapp.com',
    storageBucket: 'digital-burnout-821da.firebasestorage.app',
    measurementId: 'G-NNGC5QTDKE',
  );
}
